# Week 1 - Lesson 4 - Linear Algebra

In [2]:
import numpy as np

### 1. Scalar Inner Product: ```np.dot()```

- Calculates scalar product of two vectors or the matrix product of two matrices.
- **Signature**: ```np.dot(a, b, out=None)```

In [3]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])

# Scalar inner product
dot_prod = np.dot(v1, v2)
print("np.dot(v1, v2) = ", dot_prod)

# Matrix multiplication
M1 = np.array([[1,2], [3,4]])
M2 = np.array([[5,6], [7,8]])
mat_prod = np.dot(M1, M2)
print("np.dot(M1, M2) = \n", mat_prod)

np.dot(v1, v2) =  32
np.dot(M1, M2) = 
 [[19 22]
 [43 50]]


### 2. Outter Product: ```np.cross()```

- Calculates the outter (vector) product of two 3-dimensional vectors.
- **Signature**: ```np.cross(a, b, axisa=-1, axisb=-1, axisc=-1, axis=None, out=None)```

In [3]:
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

cross_product = np.cross(a, b)
print("np.cross(a, b) = ", cross_product)

np.cross(a, b) =  [0 0 1]


### 3. Norm (Size): ```np.linalg.norm()```

- Calculates the norm (size) of a vector or a matrix (L1, L2, etc.)
- **Signature**: ```np.linalg.norm(x, ord=None, axis=None, keepdims=False)```

In [ ]:
vector = np.array([3, 4])
norm_L2 = np.linalg.norm(vector)
norm_L1 = np.linalg.norm(vector, ord=1)
print("L2 norm of vector = ", norm_L2) # 5.0
print("L1 norm of vector = ", norm_L1) # 7.0

L2 norm of vector =  5.0
L1 norm of vector =  7.0


### 4. Eigenvalues and Eigenvectors: ```np.linalg.eig()```

- Calculates the Eigenvalue and Eigenvector of a square matrix.
- **Signature**: ```np.linalg.eig(a)```

In [5]:
A = np.array([[2, 0], [0, 3]])
W, v = np.linalg.eig(A)
print("Eigenvalues of A = ", W)
print("Eigenvectors of A = \n", v)

Eigenvalues of A =  [2. 3.]
Eigenvectors of A = 
 [[1. 0.]
 [0. 1.]]


### Singular Value Decomposition: ```np.linalg.svd()```

- Calculates the singular value decomposition (SVD) of a matrix: ```A = U * S *Vh```.
- **Signature**: ```np.linalg.svd(a, full_matrices=True, compute_uv=True, hermitian=False)```

In [6]:
B = np.array([[1, 2, 3], [4, 5, 6]])
U, S, Vh = np.linalg.svd(B, full_matrices=False)
print("U = \n", U)
print("S = ", S)
print("Vh = \n", Vh)

U = 
 [[-0.3863177  -0.92236578]
 [-0.92236578  0.3863177 ]]
S =  [9.508032   0.77286964]
Vh = 
 [[-0.42866713 -0.56630692 -0.7039467 ]
 [ 0.80596391  0.11238241 -0.58119908]]
