# Week 1 - Lesson 1 - Numpy

In [2]:
import numpy as np

### 1. ```np.array()```

- Defines a **ndarray** out of a list/tuple
- **Signature**: ```np.array(object, dtype=None, copy=True, order='K', ndmin=0)``` 

In [3]:
# 1D (1 dimensional) array
a = np.array([1, 2, 3], dtype=float)
print(a, a.dtype)

# 2D (2 dimensional) array
b = np.array([[1, 2, 3], [4, 5, 6]], order='C')
print(b, b.dtype, b.shape)

[1. 2. 3.] float64
[[1 2 3]
 [4 5 6]] int32 (2, 3)


### 2. ```np.zeros()``` & ```np.ones()```

- Defines an array filled with **zeros** or **ones** based on given shape.
- **Signature**: ```np.zeros(shape, dtype=float, order='C')``` / ```np.ones(shape, dtype=None, order='C')```

In [4]:
zeros = np.zeros((2, 3), dtype=int)
ones = np.ones((4))
print(zeros, ones)

[[0 0 0]
 [0 0 0]] [1. 1. 1. 1.]


### 3. ```np.eye()```

- Defines an identity matrix.
- **Signature**: ```np.eye(N, M=None, k=0, dtype=float, order='C')```

In [6]:
I = np.eye(3, dtype=int)
I2 = np.eye(3, 3, k=1)
print(I, I2)

[[1 0 0]
 [0 1 0]
 [0 0 1]] [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


### 4. ```reshape()```, ```T``` (transpose)

- Reshapes the array and gets transposed
- **Signature**: ```a.reshape(newshape) / a.T```

In [7]:
A = np.arange(10)
B = A.reshape(2, 5)
print(B)
print(B.T)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


### 5. Scalar & Matrix Multiplication: ```np.dot()``` / ```np.matmul()```

- Scalar, vector or matrix multiplication
- **Signature**: np.dot(a, b, out=None) / np.matmul(a, b, out=None)

In [7]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.dot(x, y)) # Scalar inner product

M = np.arange(9).reshape(3, 3)
print(np.matmul(M, x))

32
[ 8 26 44]


### 6. Random Matrix: ```np.random.rand()```

- Uniform distribution in the range of [0, 1)
- **Signature**: ```np.random.rand(d0, d1, ..., dn)```

In [8]:
R = np.random.rand(2, 2)
print(R)

[[0.29503822 0.0408498 ]
 [0.05909694 0.79357084]]


### 7. Determinant & Inverse: ```np.linlg.det()``` / ```np.linlg.inv()```

- Calculates the determinant and inverse of the given matrix
- **Signature**: ```np.linlg.det(a)``` / ```np.linglg.inv(a)```

In [9]:
A = np.array([[1, 2], [3, 4]])
print("det=", np.linalg.det(A))
print("inv=", np.linalg.inv(A))

det= -2.0000000000000004
inv= [[-2.   1. ]
 [ 1.5 -0.5]]
